### ISSUE TITLE
Add support for NutritionZ

### ISSUE THREAD

**Issue by YOUNIN15** [Ninjdai1/CornExpansion#8]
Most of the [Let's Do] series has support for NutritionZ. Although [Let's Do] Farm&Charm has not yet added support, I was told they will soon do so.

**Comment by Ninjdai1** [comment]
NutritionZ now had built-in support for Farm&Charm aswell as CornExpansion (see https://github.com/xR4YM0ND/NutritionZ/tree/1.20/src/main/resources/resourcepacks/cornexpansion_nutrition_compat & https://github.com/xR4YM0ND/NutritionZ/tree/1.20/src/main/resources/resourcepacks/farm_and_charm_nutrition_compat)
